[package]
name = "valkey-wasm"
edition = "2024"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "valkey_wasm"

[dependencies]
valkey-module = "0.1.10"
wasmtime = { version = "41", default-features = false, features = ["component-model", "cranelift", "runtime"] }
anyhow = "1"
sha2 = "0.10"

[features]
# Use the system allocator instead of Valkey's allocator in tests.
enable-system-alloc = ["valkey-module/enable-system-alloc"]
